import Head from "next/head";
import BagicHome from "@/components/PageElements/BagicHome";
import styles from "./styles.module.css";
import { useEffect } from "react";
import MainParticles from "@/components/PageElements/Particles/mainParticles";

import { useRecoilState } from "recoil";
import { indexBGMElement, indexBGMState } from "@/components/Game/atom";

export default function Home() {
  const [indexBGM, setIndexBGM] = useRecoilState(indexBGMElement);
  const [isPlaying, setIsPlaying] = useRecoilState(indexBGMState);

  useEffect(() => {
    if (!indexBGM) {
      const newAudio = new Audio("/sounds/bgm.mp3");
      //@ts-ignore
      setIndexBGM(newAudio);
    }
    if (indexBGM && !isPlaying) {
      (indexBGM as HTMLAudioElement).loop = true;
      // (indexBGM as HTMLAudioElement).play();
      setIsPlaying(true);
    }
  }, [indexBGM]);

  return (
    <>
      <Head>
        <title>Jigsaw Puzzle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-[url('/images/ccccuuurrentEmptySpace.png')] bg-cover bg-center h-screen">
        {/* {isFiveMinutes? ""  : <MainParticles />} */}
        <div className={styles.indexbox}>
          <div className={styles.indexText}>
            DYNAMIC <br />
            PUZZLE
          </div>
        </div>
        <div className="absolute justify-end items-end flex w-1/4 h-4/5">
          <BagicHome />
        </div>
      </div>
    </>
  );
}
